# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/suhana9010/5e3127bf6541f9c02a741e55a601ebd4/untitled2.ipynb
"""

from nltk.chat.util import Chat, reflections

pairs=[
       ['my name is (.*)', ['hi %1']],
       ['(hi|hello|hey|holla|hola)',['hey there!', 'hi there!', 'haayyy!']],
       ['(.*) in (.*) is fun', ['%1 in %2 is indeed fun']],
       ['(.*)(location|city) ?', 'Tokyo, Japan'],
       ['(.*) created you ?', ['shannu did using NLTK']],
       ['how is the weather in (.*)', ['the weather in %1 is amazing like always']],
       ['(.*)help(.*)', ['I can help you']],
       ['(.*) your name ?', ['my name is Chitti!']],
       ['(hi chitti|hello chitti|hey chitti|holla chitti|hola chitti)', ['hey dear!', 'hi dear!', 'haayyy dear!','hai dear!']],
       ["what's up?", ['Noting much']],
       ['(I love you|I like you|i love u)', ['Oh! really? This is the great day','I like you too', 'thank you']],
       ['(.*) are you?', ['Is it required to remind you! Ofcourse,Your friend Chitti']],
       ['(.*)(my exam|is my exam)', ['All the best!you are gonna rock it','Best of luck','Best wishes from my side','Have a nice day']],
       ['(.*) your home?', ['In Guntur']],
       
]

my_dummy_reflections={
    'go': 'gone',
    'hello': 'hey there'
}

chat=Chat(pairs, my_dummy_reflections)
#chat._substitute('go hello')
chat.converse()
